### ISSUE TITLE
No APK for v1.0.3?

### ISSUE THREAD

**Issue by IzzySoft** [SecUSo/privacy-friendly-tape-measure#10]
Looks like you've missed to attach the `.apk` to the latest release. Could you please do so until your app is listed at F-Droid? Thanks in advance!

**Comment by IzzySoft** [comment]
Any chance?

**Comment by IzzySoft** [comment]
Looks like I'm being ignored …

**Comment by Kamuno** [comment]
Wow, I am so sorry. Doing it right now.

**Comment by Kamuno** [comment]
done, sorry that it took so long.....
