### ISSUE TITLE
tape measure review F-Droid Store

### ISSUE THREAD

**Issue by jindam-vani** [SecUSo/privacy-friendly-tape-measure#15]
@Kamuno @udenr 
* 
```
https://secuso.aifb.kit.edu/english/Tape_Measure_and_Ruler.php
```
* **the tape measure is under review. (The F-Droid Store is an open source software store where you can download the APK-file of the app.....**
* please look into the above statement and update appropriately

**Comment by udenr** [comment]
Thank you for pointing this out. I have updated the page.
